---
- name: Set fallback value for if distribution is not defined
  set_fact:
    ansible_distribution: '{{ ansible_distribution | default(ansible_lsb["id"], true) }}'
  when:
    - ansible_distribution is not defined

- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian 64-bit"
  when:
    - ansible_distribution != 'Debian'
    - ansible_architecture != 'x86_64'

- name: Check Required Variable 'block_device' if 'enable_zfs' or 'enable_lvm'
  fail: 
    msg: "Required Variable 'block_device' is Required"
  when:
    - enable_zfs == 'true' or enable_lvm == 'true'
    - block_device is not defined

- name: Make Sure 'enable_lvm' is false When 'enable_zfs' is true
  set_fact:
    enable_lvm: 'false'
  when:
    - enable_zfs == 'true'

- name: Make Sure 'enable_zfs' is false When 'enable_lvm' is true
  set_fact:
    enable_zfs: 'false'
  when:
    - enable_lvm == 'true'
